//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int StockId { get; set; }
        public int StockQuantity { get; set; }
        public string StockUnitOfMeasure { get; set; }
        public System.DateTime StockSupplyDate { get; set; }
        public System.DateTime StockExpirationDate { get; set; }
        public decimal StockPurchasePrice { get; set; }
        public decimal StockSellingPrice { get; set; }
        public int ProductId { get; set; }
        public bool IsEnabled { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
